// Generated by CoffeeScript 1.3.3
(function() {
  var arcoApp;

  arcoApp = angular.module('arco', ['ngRoute']);

  arcoApp.config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/login', {
        templateUrl: 'partials/auth/login.html',
        controller: 'AuthLoginCtrl'
      }).when('/my-scores', {
        templateUrl: 'partials/score/list.html',
        controller: 'ScoreListCtrl'
      }).otherwise({
        redirectTo: '/'
      });
    }
  ]);

  arcoApp.controller('ScoreListCtrl', [
    '$scope', 'Score', function($scope, Score) {
      return $scope.scores = [];
    }
  ]);

  arcoApp.controller('AuthLoginCtrl', [
    '$scope', 'Auth', function($scope, Auth) {
      return $scope.login = Auth.login;
    }
  ]);

  arcoApp.factory('Score', [
    '$http', function($http) {
      return {};
    }
  ]);

  arcoApp.factory('Auth', [
    '$http', function($http) {
      return {
        login: function() {
          return $http.post('/auth').success(function(data, status, headers, config) {
            return console.log('LOGIN success', data, status);
          }).error(function(data, status, headers, config) {
            return console.log('LOGIN error', data, status);
          });
        }
      };
    }
  ]);

}).call(this);
